# Generated by Django 6.0.4 on 2026-04-17 05:33

import core.db.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Account code (e.g., 10101 for Cash)', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_nepali', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('is_system', models.BooleanField(default=False, help_text='System accounts cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('opening_balance', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('-999999999999.9999')), django.core.validators.MaxValueValidator(Decimal('999999999999.9999'))])),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'accounts_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(help_text='e.g., 2080/81', max_length=10)),
                ('start_date', core.db.fields.BSDateField()),
                ('end_date', core.db.fields.BSDateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retained_earnings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='tenants.tenant')),
            ],
            options={
                'db_table': 'accounts_fiscalyear',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, help_text='Unique transaction reference (e.g., JV-2024-00001)', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('bs_date', core.db.fields.BSDateField()),
                ('narration', models.TextField(help_text='Transaction description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('total_debit', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('total_credit', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('is_vat_applicable', models.BooleanField(default=False)),
                ('vat_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=255)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('source_type', models.CharField(blank=True, help_text='Source document type (e.g., invoice, purchase)', max_length=50)),
                ('source_id', models.IntegerField(blank=True, help_text='Source document ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'accounts_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Debit amount (positive number)', max_digits=20)),
                ('credit', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Credit amount (positive number)', max_digits=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.transaction')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'accounts_ledgerentry',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'type', 'is_active'], name='accounts_ac_tenant__117884_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'parent', 'is_active'], name='accounts_ac_tenant__5767a8_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'code', 'is_active'], name='accounts_ac_tenant__f4763d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('tenant', 'year_name')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'date', 'status'], name='accounts_tr_tenant__c012b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='accounts_tr_tenant__5c1928_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'source_type', 'source_id'], name='accounts_tr_tenant__c6e972_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('tenant', 'reference_number')},
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'account', 'created_at'], name='accounts_le_tenant__c5c3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['tenant', 'transaction', 'account'], name='accounts_le_tenant__0b41d5_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='accounts_le_account_a66391_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='debit_non_negative', violation_error_message='Debit amount cannot be negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='credit_non_negative', violation_error_message='Credit amount cannot be negative'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _connector='OR'), name='debit_or_credit_required', violation_error_message='Either debit or credit must be greater than zero'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gt', 0), ('debit__gt', 0), _negated=True), name='not_both_debit_and_credit', violation_error_message='Cannot have both debit and credit in same entry'),
        ),
    ]
