# Generated by Django 6.0.4 on 2026-04-17 05:33

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('pan', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('vat_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', encrypted_model_fields.fields.EncryptedEmailField(blank=True)),
                ('fiscal_year_start', models.IntegerField(default=4, help_text='Month number when fiscal year starts (4 = Shrawan)')),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants_tenant',
                'indexes': [models.Index(fields=['slug', 'is_active'], name='tenants_ten_slug_7c647c_idx'), models.Index(fields=['is_verified', 'created_at'], name='tenants_ten_is_veri_437467_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_starting_number', models.IntegerField(default=1)),
                ('invoice_terms', models.TextField(blank=True, default='Payment due within 30 days. Late payments subject to 2% monthly interest.')),
                ('default_print_template', models.CharField(choices=[('standard', 'Standard A4'), ('compact', 'Compact A4'), ('thermal80', 'Thermal 80mm'), ('thermal58', 'Thermal 58mm')], default='standard', max_length=50)),
                ('enable_inventory', models.BooleanField(default=True)),
                ('enable_multi_currency', models.BooleanField(default=False)),
                ('enable_api_access', models.BooleanField(default=False)),
                ('esewa_merchant_id', models.CharField(blank=True, max_length=100)),
                ('khalti_public_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_tenantsettings',
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='External auth provider user ID', max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('operator', 'Operator'), ('viewer', 'Viewer')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
                'db_table': 'tenants_tenantuser',
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='tenants_ten_user_id_b140bc_idx'), models.Index(fields=['tenant', 'role'], name='tenants_ten_tenant__55a2cb_idx')],
                'unique_together': {('tenant', 'user_id')},
            },
        ),
    ]
