# Generated by Django 6.0.4 on 2026-04-17 05:33

import core.db.fields
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('warehouse_location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('count_date', models.DateField()),
                ('bs_count_date', core.db.fields.BSDateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'inventory_inventorycount',
                'unique_together': {('tenant', 'reference_number')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='SKU or product code', max_length=100)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('name_nepali', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='Pcs', help_text='Unit of measurement', max_length=50)),
                ('unit_nepali', models.CharField(blank=True, max_length=50)),
                ('alternate_unit', models.CharField(blank=True, max_length=50)),
                ('conversion_factor', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='1 base unit = ? alternate units', max_digits=20)),
                ('is_vat_applicable', models.BooleanField(default=False)),
                ('vat_rate', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=6)),
                ('vat_category', models.CharField(blank=True, max_length=50)),
                ('selling_price', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard selling price', max_digits=20)),
                ('purchase_price', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Last purchase price / average cost', max_digits=20)),
                ('standard_cost', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard cost for valuation', max_digits=20)),
                ('min_selling_price', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Minimum allowed selling price', max_digits=20)),
                ('max_discount_percent', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum allowed discount %', max_digits=5)),
                ('stock_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Current stock on hand', max_digits=20)),
                ('reserved_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Reserved for orders', max_digits=20)),
                ('available_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Available for sale (stock - reserved)', max_digits=20)),
                ('reorder_level', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Reorder point', max_digits=20)),
                ('reorder_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Suggested reorder quantity', max_digits=20)),
                ('max_stock_level', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Maximum desired stock', max_digits=20)),
                ('warehouse_location', models.CharField(blank=True, max_length=100)),
                ('bin_location', models.CharField(blank=True, max_length=50)),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO - First In, First Out'), ('lifo', 'LIFO - Last In, First Out'), ('average', 'Weighted Average'), ('standard', 'Standard Cost')], default='average', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dimensions_cm', models.CharField(blank=True, help_text='LxWxH in cm', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('track_inventory', models.BooleanField(default=True, help_text='If false, stock is not tracked (service items)')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_asset_items', to='accounts.account')),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_purchase_items', to='accounts.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sales_items', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_inventoryitem',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, help_text='Quantity according to system', max_digits=20)),
                ('counted_quantity', core.db.fields.FiscalDecimalField(blank=True, decimal_places=4, help_text='Actual counted quantity', max_digits=20, null=True)),
                ('difference', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0'), help_text='counted - system', max_digits=20)),
                ('is_counted', models.BooleanField(default=False)),
                ('is_adjusted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('counted_by', models.CharField(blank=True, max_length=255)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_inventorycountline',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('receipt', 'Goods Receipt'), ('issue', 'Goods Issue'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return_in', 'Sales Return'), ('return_out', 'Purchase Return'), ('production_in', 'Production'), ('production_out', 'Consumption'), ('damage', 'Damage/Loss')], max_length=20)),
                ('quantity', core.db.fields.FiscalDecimalField(decimal_places=4, help_text='Positive for in, negative for out (absolute value stored)', max_digits=20)),
                ('unit_cost', core.db.fields.FiscalDecimalField(blank=True, decimal_places=4, help_text='Cost per unit at time of movement', max_digits=20, null=True)),
                ('total_cost', core.db.fields.FiscalDecimalField(blank=True, decimal_places=4, help_text='Total cost (quantity * unit_cost)', max_digits=20, null=True)),
                ('reference_type', models.CharField(blank=True, help_text='Source document type', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, help_text='Source document ID', null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('bs_date', core.db.fields.BSDateField()),
                ('from_location', models.CharField(blank=True, max_length=100)),
                ('to_location', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.transaction')),
            ],
            options={
                'db_table': 'inventory_stockmovement',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('reserved_for_type', models.CharField(help_text='e.g., sales_order, production_order', max_length=50)),
                ('reserved_for_id', models.IntegerField()),
                ('reserved_for_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fulfilled_quantity', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0'), max_digits=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'inventory_stockreservation',
            },
        ),
        migrations.CreateModel(
            name='SupplierPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(db_index=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('unit_price', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('min_order_qty', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('1'), max_digits=20)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='inventory.inventoryitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'inventory_supplierpricelist',
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='inventory_i_tenant__0daf6e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'is_active', 'stock_quantity'], name='inventory_i_tenant__d72adb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'barcode'], name='inventory_i_tenant__8a9dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'track_inventory', 'stock_quantity', 'reorder_level'], name='inventory_i_tenant__c6995b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorycountline',
            unique_together={('count', 'item')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'item', 'date'], name='inventory_s_tenant__fee686_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'type', 'date'], name='inventory_s_tenant__70ae9f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'reference_type', 'reference_id'], name='inventory_s_tenant__a59ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'batch_number'], name='inventory_s_tenant__9bdeee_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'expiry_date'], name='inventory_s_item_id_19d063_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['tenant', 'item', 'is_active'], name='inventory_s_tenant__40b308_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['reserved_for_type', 'reserved_for_id'], name='inventory_s_reserve_7d33c4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierpricelist',
            index=models.Index(fields=['tenant', 'item', 'is_preferred'], name='inventory_s_tenant__5de621_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierpricelist',
            unique_together={('tenant', 'supplier_id', 'item')},
        ),
    ]
