# Generated by Django 6.0.4 on 2026-04-17 05:33

import core.db.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('name_nepali', models.CharField(blank=True, max_length=255)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government'), ('foreign', 'Foreign')], default='company', max_length=20)),
                ('pan_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('vat_registered', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True)),
                ('address_nepali', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('credit_limit', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('credit_days', models.IntegerField(default=30)),
                ('default_discount_percent', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_receivables', to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'invoicing_customer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('manual_reference', models.CharField(blank=True, help_text='External PO number or reference', max_length=100)),
                ('invoice_type', models.CharField(choices=[('tax', 'Tax Invoice'), ('retail', 'Retail Invoice'), ('export', 'Export Invoice'), ('deemed', 'Deemed Export')], default='tax', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('credit_note', 'Credit Note Issued')], db_index=True, default='draft', max_length=20)),
                ('billed_name', models.CharField(max_length=255)),
                ('billed_address', models.TextField(blank=True)),
                ('billed_pan', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('bs_date', core.db.fields.BSDateField()),
                ('due_date', models.DateField()),
                ('bs_due_date', core.db.fields.BSDateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_vat_applicable', models.BooleanField(default=True)),
                ('vat_rate', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Standard is 13% for Nepal', max_digits=5)),
                ('subtotal', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('discount_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('discount_percent', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxable_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vat_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('exempt_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('zero_rated_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('total_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('amount_paid', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('amount_due', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('ird_synced', models.BooleanField(db_index=True, default=False)),
                ('ird_bill_id', models.CharField(blank=True, max_length=100)),
                ('ird_qr_data', models.TextField(blank=True)),
                ('ird_sync_error', models.TextField(blank=True)),
                ('ird_synced_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('print_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoicing.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounts.transaction')),
            ],
            options={
                'db_table': 'invoicing_invoice',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField()),
                ('bs_date', core.db.fields.BSDateField()),
                ('subtotal', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('vat_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('total_amount', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('reason', models.CharField(choices=[('return', 'Goods Return'), ('discount', 'Post-sale Discount'), ('error', 'Invoice Error'), ('damage', 'Damaged Goods'), ('other', 'Other')], max_length=20)),
                ('reason_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('ird_synced', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.transaction')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='invoicing.invoice')),
            ],
            options={
                'db_table': 'invoicing_creditnote',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('quantity', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit', models.CharField(default='Pcs', max_length=20)),
                ('unit_price', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('unit_cost', core.db.fields.FiscalDecimalField(blank=True, decimal_places=4, help_text='Cost at time of sale (for margin analysis)', max_digits=20, null=True)),
                ('discount_percent', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('line_discount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vat_type', models.CharField(choices=[('standard', 'Standard (13%)'), ('zero_rated', 'Zero Rated (0%)'), ('exempt', 'Exempt'), ('export', 'Export (0%)')], default='standard', max_length=20)),
                ('vat_rate', core.db.fields.FiscalDecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('line_total', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('vat_amount', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('total_with_vat', core.db.fields.FiscalDecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoicing.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.inventoryitem')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'invoicing_invoiceline',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bs_date', core.db.fields.BSDateField()),
                ('amount', core.db.fields.FiscalDecimalField(decimal_places=4, max_digits=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('connectips', 'ConnectIPS'), ('card', 'Card/Pos'), ('credit_note', 'Credit Note')], max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number, transaction ID, etc.', max_length=100)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, limit_choices_to={'type': 'asset'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='accounts.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payment', to='accounts.transaction')),
            ],
            options={
                'db_table': 'invoicing_invoicepayment',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'pan_number'], name='invoicing_c_tenant__513aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='invoicing_c_tenant__658bfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status', 'date'], name='invoicing_i_tenant__1c8512_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='invoicing_i_tenant__df2f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'due_date'], name='invoicing_i_tenant__6858ef_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'ird_synced'], name='invoicing_i_tenant__105664_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'fiscal_year', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('tenant', 'credit_number')},
        ),
    ]
