# Generated by Django 6.0.4 on 2026-04-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=50)),
                ('entity_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(max_length=20)),
                ('changed_by', models.CharField(max_length=255)),
                ('old_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id', 'created_at'], name='audit_logs_tenant__87d190_idx'), models.Index(fields=['tenant', 'action', 'created_at'], name='audit_logs_tenant__b6d72a_idx')],
            },
        ),
    ]
