# Generated by Django 6.0.4 on 2026-04-17 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=30)),
                ('parameters', models.JSONField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(default=0)),
                ('generated_by', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'reports_reportexport',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('trial_balance', 'Trial Balance'), ('profit_loss', 'Profit & Loss'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement'), ('ledger', 'General Ledger'), ('bank_reconciliation', 'Bank Reconciliation'), ('vat_report', 'VAT Report'), ('tds_report', 'TDS Report'), ('receivables', 'Receivables Aging'), ('payables', 'Payables Aging'), ('inventory', 'Inventory Report'), ('sales', 'Sales Report'), ('purchase', 'Purchase Report')], max_length=30)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('date_format', models.CharField(choices=[('ad', 'Gregorian (AD)'), ('bs', 'Bikram Sambat (BS)')], default='bs', max_length=10)),
                ('show_zero_balances', models.BooleanField(default=False)),
                ('compare_with_previous', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenants.tenant')),
            ],
            options={
                'db_table': 'reports_savedreport',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('recipients', models.JSONField(default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='tenants.tenant')),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.savedreport')),
            ],
            options={
                'db_table': 'reports_reportschedule',
            },
        ),
    ]
